package io.github.javamaintainers.jmk.report;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import io.github.javamaintainers.jmk.model.AnalysisReport;
import io.github.javamaintainers.jmk.model.ChangedFile;
import io.github.javamaintainers.jmk.model.DependencyChange;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/** Renders analysis reports as Markdown or JSON. */
public final class ReportRenderer {
  private final ObjectMapper mapper =
      new ObjectMapper().enable(SerializationFeature.INDENT_OUTPUT);

  public String toMarkdown(AnalysisReport report) {
    StringBuilder md = new StringBuilder();
    md.append("## Java Maintainer Kit Report\n\n");
    md.append("Comparing `")
        .append(report.baseRef())
        .append("` → `")
        .append(report.headRef())
        .append("`\n\n");

    md.append("### Summary\n\n");
    md.append("| Metric | Value |\n|---|---:|\n");
    md.append("| Changed files | ").append(report.changedFiles().size()).append(" |\n");
    md.append("| Impacted modules | ").append(report.impactedModules().size()).append(" |\n");
    md.append("| Dependency changes | ").append(report.dependencyChanges().size()).append(" |\n");
    md.append("| Risk signals | ").append(report.risks().size()).append(" |\n\n");

    md.append("### Impacted modules\n\n");
    if (report.impactedModules().isEmpty()) {
      md.append("_None detected_\n\n");
    } else {
      for (String module : report.impactedModules()) {
        md.append("- `").append(module).append("`\n");
      }
      md.append('\n');
    }

    md.append("### Dependency changes\n\n");
    if (report.dependencyChanges().isEmpty()) {
      md.append("_No POM dependency changes detected_\n\n");
    } else {
      Map<String, List<DependencyChange>> byModule =
          report.dependencyChanges().stream()
              .collect(
                  Collectors.groupingBy(
                      DependencyChange::moduleArtifactId, LinkedHashMap::new, Collectors.toList()));
      for (Map.Entry<String, List<DependencyChange>> entry : byModule.entrySet()) {
        md.append("#### Module `").append(entry.getKey()).append("`\n\n");
        for (DependencyChange change : entry.getValue()) {
          md.append("- ").append(change.summary()).append('\n');
        }
        md.append('\n');
      }
    }

    md.append("### Risk signals\n\n");
    if (report.risks().isEmpty()) {
      md.append("_No automatic risk signals_\n\n");
    } else {
      for (String risk : report.risks()) {
        md.append("- ").append(risk).append('\n');
      }
      md.append('\n');
    }

    md.append("### Recommendations\n\n");
    for (String recommendation : report.recommendations()) {
      md.append("- ").append(recommendation).append('\n');
    }
    md.append('\n');

    md.append("<details>\n<summary>Changed files (").append(report.changedFiles().size()).append(")</summary>\n\n");
    for (ChangedFile file : report.changedFiles()) {
      md.append("- `")
          .append(file.type())
          .append("` ")
          .append(file.path())
          .append('\n');
    }
    md.append("\n</details>\n\n");
    md.append("---\n");
    md.append("_Generated by [Java Maintainer Kit](https://github.com/blueskyno6/java-maintainer-kit)_\n");
    return md.toString();
  }

  public String toJson(AnalysisReport report) throws Exception {
    Map<String, Object> payload = new LinkedHashMap<>();
    payload.put("baseRef", report.baseRef());
    payload.put("headRef", report.headRef());
    payload.put("changedFiles", report.changedFiles().size());
    payload.put("impactedModules", report.impactedModules());
    payload.put(
        "dependencyChanges",
        report.dependencyChanges().stream().map(DependencyChange::summary).toList());
    payload.put("risks", report.risks());
    payload.put("recommendations", report.recommendations());
    payload.put(
        "files",
        report.changedFiles().stream()
            .map(f -> Map.of("path", f.path(), "type", f.type().name()))
            .toList());
    return mapper.writeValueAsString(payload);
  }
}
